theme: jekyll-theme-slate
baseurl: ""
url: "https://syagmur.github.io"
title: Kinematic Optimization of an Underactuated Anthropomorphic Prosthetic Hand
description: Serial port communication and real-time EMG classification code
markdown: kramdown
future: true

gems:
    - jekyll-sitemap
    - jekyll-coffeescript
    - jekyll-paginate
    - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  
